language: scala
jdk: openjdk8
scala:
  - 2.13.4
  - 2.12.9
sudo: false
before_install: umask 0022
script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt -jvm-opts travis/jvmopts.compile run
  - sbt -jvm-opts travis/jvmopts.test test